#logging:
#  level:
#    root: TRACE
spring:
  profiles.active: ${PROFILE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL}
aws:
  s3:
    key: ${S3_KEY}
    secret: ${S3_SECRET}
