spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      search.backend.directory.root: /mnt/efs
aws:
  s3:
    key: ${S3_KEY}
    secret: ${S3_SECRET}
